### ISSUE TITLE
Prisma 5 support

### ISSUE THREAD

**Issue by jerembdn** [omar-dulaimi/prisma-joi-generator#9]
## Problem

Got this error on NestJS with Prisma v5 and latest version of prisma-joi-generator :

```
/home/.../api/src/generated/validation/schemas/enums/QueryMode.schema.ts:3
export const QueryModeSchema = Joi.string().valid(...["default","insensitive"])
                                   ^
TypeError: Cannot read properties of undefined (reading 'string')
    at Object.<anonymous> (/home/.../api/src/generated/validation/schemas/enums/QueryMode.schema.ts:3:36)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (/home/.../api/src/generated/validation/schemas/objects/StringFilter.schema.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
```

Is prisma-joi-generator supporting Prisma v5 ?

**Comment by omar-dulaimi** [comment]
v1.0.0 now finally supports latest prisma version.
